export type FinancePlace={id:string;name:string;product:string;status:'live-product'|'live-pilot'|'opportunity';target:string|null;description:string;sourceUrl:string|null;sourceLabel:string;date:string|null};
export const FINANCE_PLACES:FinancePlace[]=[
{id:'jpmcoin',name:'J.P. Morgan',product:'JPM Coin (JPMD)',status:'live-product',target:'base',description:'A bank deposit token for institutional clients, available on Base. This connection represents JPM Coin, not all of J.P. Morgan’s business.',sourceUrl:'https://www.jpmorgan.com/payments/newsroom/jpm-coin-usd-deposit-token-institutional-clients',sourceLabel:'J.P. Morgan launch announcement',date:'2025-11-12'},
{id:'buidl',name:'BlackRock',product:'BUIDL',status:'live-product',target:'ethereum',description:'A tokenized fund launched on Ethereum for eligible investors. This route shows its Ethereum connection, not BlackRock’s entire portfolio or every BUIDL deployment.',sourceUrl:'https://www.nasdaq.com/press-release/blackrock-launches-its-first-tokenized-fund-buidl-on-the-ethereum-network-2024-03-20',sourceLabel:'BlackRock launch release',date:'2024-03-20'},
{id:'benji',name:'Franklin Templeton',product:'BENJI / FOBXX',status:'live-product',target:'arbitrum',description:'Tokenized fund shares with deployments including Arbitrum One, Ethereum and Base. This selected route highlights Arbitrum One.',sourceUrl:'https://digitalassets.franklintempleton.com/benji/benji-contracts/',sourceLabel:'Official BENJI contract directory',date:'2024-08-08'},
{id:'visa',name:'Visa',product:'Stablecoin settlement',status:'live-pilot',target:'ethereum',description:'Visa’s documented live settlement pilot supports Ethereum and Base among several networks. This is not a claim that all Visa card transactions run onchain.',sourceUrl:'https://investor.visa.com/news/news-details/2026/Visa-Accelerates-Stablecoin-Momentum-Adding-Five-Blockchains-for-Settlement/',sourceLabel:'Visa announcement',date:'2026-04-29'},
{id:'future-banks',name:'Banks',product:'Future opportunity',status:'opportunity',target:null,description:'A schematic space for potential new products, participants and connections. This is not an announced commitment or a claim that the banking sector has no existing onchain activity.',sourceUrl:null,sourceLabel:'Illustrative future connection',date:null},
{id:'future-insurance',name:'Insurance',product:'Future opportunity',status:'opportunity',target:null,description:'A schematic space for possible future applications and participation. It is a design scenario, not a forecast, measured flow or commitment by an institution.',sourceUrl:null,sourceLabel:'Illustrative future connection',date:null}
];
export function financeLabel(status:FinancePlace['status']){return status==='live-product'?'Documented live product':status==='live-pilot'?'Documented live pilot':'Illustrative opportunity'}
