import {useRef,type RefObject} from 'react';
import {exact,short,type Snapshot} from './data';
import type {Network} from './networks';
import {financeLabel,FINANCE_PLACES,type FinancePlace} from './finance';
import type {StakingSnapshot} from './staking';
import {isTelemetryFresh,type TelemetrySnapshot} from './telemetry';
import {bridgeCoverage,type BridgeSnapshot} from './bridges';
import {shortTime,age} from './live-hooks';

export function FinanceCard({place,onTarget}:{place:FinancePlace;onTarget:(id:string)=>void}){
 return <div className="finance-card-content"><div className="card-top"><span className="card-tag">THE WIDER FINANCIAL SYSTEM</span></div>
 <h1>{place.name}</h1><span className={'finance-status '+place.status}>{financeLabel(place.status)}</span><h2 className="finance-product">{place.product}</h2><p className="finance-description">{place.description}</p>
 {place.target&&<button className="connection-link" onClick={()=>onTarget(place.target!)}>Explore {place.target==='ethereum'?'Ethereum':place.target==='base'?'Base':'Arbitrum One'} connection ↗</button>}
 {place.sourceUrl&&<a className="institution-source" href={place.sourceUrl} target="_blank" rel="noreferrer">{place.sourceLabel} ↗</a>}
 {place.date&&<p className="finance-date">Documented {place.date}</p>}<p className="institution-note">{place.status==='opportunity'?'Dashed paths indicate a possible future, not an announced commitment.':'The static path documents a product relationship. It does not depict measured money flowing from the institution.'}</p></div>
}
export function StakingCard({data,onHall}:{data:StakingSnapshot;onHall:()=>void}){
 return <div className="staking-card-content"><div className="card-top"><span className="card-tag">THE SECURITY FOUNDATION</span><button className="staking-back" onClick={onHall} aria-label="Back to Ethereum town hall">↗</button></div>
 <h1>ETH at stake.<br/>Ethereum secured.</h1><p className="staking-lead">Validators commit ETH, propose blocks and vote on Ethereum’s history.</p>
 <div className="town-big-number">{short(data.reportedStakedEth)}<span className="stake-unit"> ETH</span></div>
 <p className="town-number-caption">reported staked ETH · <a href={data.sourceUrl} target="_blank" rel="noreferrer">ethereum.org</a><br/><span>{exact(data.reportedStakedEth)} ETH · checked {data.capturedAt.slice(0,10)} {shortTime(data.capturedAt)}</span></p>
 <ol className="staking-steps"><li><span>01</span><div><strong>Put ETH at stake</strong><small>Economic commitment to the network</small></div></li><li><span>02</span><div><strong>Propose &amp; attest</strong><small>Validators agree on Ethereum’s history</small></div></li><li><span>03</span><div><strong>Secure the shared foundation</strong><small>Ethereum anchors the connected L2s</small></div></li></ol>
 <p className="staking-incentives">Correct participation earns rewards. Missed votes can incur penalties; conflicting proposals or votes can trigger slashing.</p>
 {data.warning&&<p className="staking-source-warning" role="status">{data.warning}</p>}<div className="staking-illustration-note">Reported metric, checked every 15 minutes. Its measurement time is not published. Validator lights are illustrative.</div></div>
}
function downloadRows(rows:unknown[][],name:string){const content=rows.map(row=>row.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');const url=URL.createObjectURL(new Blob([content],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000)}
export function FeedDialog({dialog,chains,telemetry,bridges,staking,historical,unit,now,onSelect}:{dialog:RefObject<HTMLDialogElement|null>;chains:Network[];telemetry:TelemetrySnapshot;bridges:BridgeSnapshot|null;staking:StakingSnapshot;historical:Snapshot;unit:number;now:number;onSelect:(id:string)=>void}){
 const observationsHeading=useRef<HTMLHeadingElement>(null);
 const select=(id:string)=>{onSelect(id);dialog.current?.close()};
 const coverage=bridges?.coverage??bridgeCoverage(false);
 const bridgeCount=coverage.filter(c=>c.bridgeStatus!=='unsupported').length,settlementCount=coverage.filter(c=>c.settlementStatus!=='unsupported').length;
 return <dialog ref={dialog} id="town-reading-guide" className="data-dialog live-dialog" aria-labelledby="town-guide-title" aria-describedby="town-guide-intro"><div className="dialog-head town-guide-head"><div><p>A SMALL TOWN. A CONNECTED ECONOMY.</p><h2 id="town-guide-title">How to read the town</h2></div><button autoFocus onClick={()=>dialog.current?.close()} aria-label="Close town guide and sources">×</button></div>
 <section className="town-reading-guide" aria-label="Visual guide">
  <p id="town-guide-intro" className="town-guide-intro">The buildings explain Ethereum’s ecosystem. The people and moving packets show selected, sourced observations.</p>
  <div className="town-guide-grid">
   <section><span className="town-guide-symbol" aria-hidden="true">◇</span><h3>The hall &amp; neighborhoods</h3><p>L2s execute their own transactions and send data or state updates to Ethereum. The central hall represents Ethereum’s settlement and consensus role. Building size is architectural, not a measure of activity.</p></section>
   <section><span className="town-guide-symbol" aria-hidden="true">♙</span><h3>The people</h3><p>Each crowd shows its network’s <strong>latest observed block</strong>, using the same rounded scale: <strong>1 walker ≈ {exact(unit)} transaction{unit===1?'':'s'}</strong>. Blocks cover different time spans. These are not users, dollars or a transactions-per-second comparison.</p></section>
   <section><span className="town-guide-symbol" aria-hidden="true">↔</span><h3>The bridges &amp; packets</h3><p>Packets replay verified observations on selected monitored routes, including recent events on arrival. Asset-bridge events differ from data or state submissions. A packet does not prove a transfer is complete; its speed is a display setting.</p></section>
   <section><span className="town-guide-symbol" aria-hidden="true">◈</span><h3>The staking lights</h3><p>The ring is symbolic. Its card shows a separately reported ETH-staking snapshot, not a live validator count. Liquid-staking tokens are not added again to that total. Staking secures Ethereum consensus; it does not guarantee every asset.</p></section>
   <section><span className="town-guide-symbol" aria-hidden="true">▥</span><h3>The wider financial district</h3><ul className="town-guide-routes"><li><i className="guide-line guide-line-live" aria-hidden="true"/>Solid: documented live product</li><li><i className="guide-line guide-line-pilot" aria-hidden="true"/>Dotted: documented pilot</li><li><i className="guide-line guide-line-future" aria-hidden="true"/>Dashed: hypothetical opportunity</li></ul><p>These static paths show product relationships, not entire institutions moving onchain or measured money flows.</p></section>
   <section><span className="town-guide-symbol" aria-hidden="true">◎</span><h3>A selected view of the ecosystem</h3><p>The town covers selected networks, products and contract routes. Quiet bridges may still have unmonitored activity. Unavailable feeds keep their last known counts with a stale label; the details below show what is monitored.</p></section>
  </div>
  <div className="town-guide-controls"><p><strong>Explore:</strong> select a building or use the neighborhood arrows. Drag to orbit; scroll to zoom. Pause and speed change animation while data keeps updating.</p><button onClick={()=>{observationsHeading.current?.scrollIntoView({block:'start'});observationsHeading.current?.focus({preventScroll:true})}}>See observations &amp; sources ↓</button></div>
 </section>
 <h2 ref={observationsHeading} id="town-observations-title" className="town-observations-title" tabIndex={-1}>Activity, sources &amp; coverage</h2>
 <div className="feed-methods"><p><strong>Blocks: every 30 seconds.</strong> Public network endpoints return the latest observed block. The town is a polling dashboard, not a complete transaction firehose.</p><p><strong>Connections: every 30 seconds.</strong> Packets replay observed contract events and verified batch submissions, including recent observations on first load. Their inclusion times and coverage are listed below.</p><p><strong>Staking: every 15 minutes.</strong> A separately labeled reported total. Future-finance paths are documented relationships or clearly marked scenarios.</p></div>
 <h3>Live network observations</h3><p>Each crowd represents the transaction count in its network’s latest observed block: one walker ≈ {exact(unit)} transactions, rounded. Blocks have different durations and transaction semantics; this is not a throughput ranking. Missing observations are not zero. Last known counts remain visible with stale labels.</p>
 <div className="table-wrap"><table><thead><tr><th>Network</th><th>Status</th><th>Block</th><th>Transactions</th><th>Block time</th><th>Checked</th></tr></thead><tbody>{chains.map(c=>{const r=telemetry.chains.find(x=>x.id===c.id);return <tr key={c.id}><td><button className="ledger-chain" onClick={()=>select(c.id)}>{c.name}</button></td><td>{isTelemetryFresh(r,now)?'Current':r?.blockNumber!==null&&r?.blockNumber!==undefined?'Stale':'Unavailable'}</td><td>{r?.explorerUrl?<a href={r.explorerUrl} target="_blank" rel="noreferrer">{r.blockNumber}</a>:'—'}</td><td>{r?.transactionCount!==null&&r?.transactionCount!==undefined?exact(r.transactionCount):'—'}</td><td>{shortTime(r?.blockTimestamp)}</td><td>{shortTime(r?.observedAt)}</td></tr>})}</tbody></table></div>
 <div className="ledger-actions"><button onClick={()=>downloadRows([['network','status','block','block_hash','transactions_in_block','block_timestamp','observed_at','finality','source'],...telemetry.chains.map(r=>[r.id,isTelemetryFresh(r,now)?'current':'stale',r.blockNumber,r.blockHash,r.transactionCount,r.blockTimestamp,r.observedAt,r.finality,r.sourceUrl])],'ethereum-town-live-blocks.csv')}>Download block observations</button><a href="/data/telemetry-provenance.json" target="_blank" rel="noreferrer">Network sources</a></div>
 <details><summary>Finality and feed details</summary>{telemetry.chains.map(r=><p key={r.id}><strong>{chains.find(c=>c.id===r.id)?.name}</strong>: {r.finality} {r.error||''} <a href={r.sourceUrl} target="_blank" rel="noreferrer">Endpoint</a>. Checked {age(r.observedAt,now)}.</p>)}</details>
 <h3>Observed Ethereum connections</h3><p>{bridges?.note||'Connecting to the monitored Ethereum routes…'}</p>
 <p><strong>Configured coverage:</strong> selected asset-bridge routes for {bridgeCount} of {coverage.length} L2s; data or settlement routes for {settlementCount} of {coverage.length}. Unsupported connections are architectural only and have no measured packets. Base and OP Mainnet batch submissions are sampled, with up to 6 newest verified calls per network in the window. These observations do not measure total traffic or asset value.</p>
 <p>Ethereum block window: {bridges?.periodStart?.slice(0,10)} {shortTime(bridges?.periodStart)} to {bridges?.observedThrough?.slice(0,10)} {shortTime(bridges?.observedThrough)}. Source checked: {bridges?.fetchedAt?.slice(0,10)} {shortTime(bridges?.fetchedAt)} ({age(bridges?.fetchedAt,now)}). {bridges?.status==='unavailable'?'Feed unavailable.':bridges?exact(bridges.events.length)+' observations in this response.':''}</p>
 <div className="coverage-list">{coverage.map(c=><section key={c.chainId}><strong>{c.chainName}</strong><span>Asset bridge: {c.bridgeStatus} · Data / settlement: {c.settlementStatus}</span><p>{c.note}</p>{c.sources.map((src,i)=><a key={src.url+':'+i} href={src.url} target="_blank" rel="noreferrer">{src.label} ↗</a>)}</section>)}</div>
 <div className="table-wrap"><table><thead><tr><th>Network / observation</th><th>Connection</th><th>Ethereum inclusion</th><th>Transaction</th></tr></thead><tbody>{bridges?.events.map(e=><tr key={e.id}><td>{e.chainName}<small className="event-stage">{e.kind==='bridge'?'Asset bridge':'Data / settlement'} · {e.stage.replaceAll('-',' ')}</small></td><td>{e.kind==='settlement'?'Data / state → Ethereum':e.direction==='l2-to-ethereum'?'L2 → Ethereum':'Ethereum → L2'}</td><td>{e.timestamp.slice(0,10)} {shortTime(e.timestamp)}<small className="event-stage">{e.finality} · finality not checked</small></td><td><a href={e.explorerUrl} target="_blank" rel="noreferrer">{e.txHash.slice(0,10)}… ↗</a></td></tr>)}{bridges&&!bridges.events.length&&<tr><td colSpan={4}>{bridges.status==='unavailable'?'Observations unavailable.':'No matching observations in this window. This does not mean no network activity.'}</td></tr>}</tbody></table></div>
 <p>Inward packets can represent batch data, commitments or state updates; they are not necessarily asset transfers. A deposit initiation is not proof of arrival on an L2. Timestamps identify the containing Ethereum block. Bridge and settlement stages are separate from Ethereum consensus finality, which this feed does not check; recent blocks may reorganize. Packet speed is a display control, not transaction speed.</p>
 <h3>ETH staking</h3><p><strong>{exact(staking.reportedStakedEth)} ETH</strong> reported by <a href={staking.sourceUrl} target="_blank" rel="noreferrer">ethereum.org</a>, which credits Dune Analytics. Source checked {staking.capturedAt.slice(0,19).replace('T',' ')} UTC. The source defines this as eligible ETH at stake but publishes no corresponding measurement time or epoch. <a href="/data/staking-snapshot.json" target="_blank" rel="noreferrer">Captured source</a>.</p>
 <p>The validator ring is symbolic, not a count or a live map of validator locations and votes. Staked ETH secures Ethereum consensus; it does not guarantee every asset in the town. <a href="https://ethereum.org/developers/docs/consensus-mechanisms/pos/" target="_blank" rel="noreferrer">Ethereum proof of stake</a>.</p>
 <h3>The wider financial system</h3><p>Solid paths show selected documented live products. Dotted paths show a documented live pilot. Dashed paths show hypothetical opportunities, with no commitment or forecast implied. These paths are not part of the measured event feed and do not represent all activity of an institution.</p>
 <div className="finance-source-list">{FINANCE_PLACES.map(p=><p key={p.id}><button className="ledger-chain" onClick={()=>select(p.id)}>{p.name} · {p.product}</button> — {financeLabel(p.status)}. {p.sourceUrl&&<a href={p.sourceUrl} target="_blank" rel="noreferrer">{p.sourceLabel} ↗</a>}</p>)}</div>
 <details><summary>Daily historical reference</summary><p>Separate completed-day context from <a href={historical.sourceUrl} target="_blank" rel="noreferrer">{historical.provider}</a>, dated {historical.dateUtc} UTC. These totals do not drive the live crowds.</p><div className="table-wrap"><table><thead><tr><th>Network</th><th>Transactions</th></tr></thead><tbody>{historical.chains.map(c=><tr key={c.id}><td>{c.name}</td><td>{exact(c.transactions)}</td></tr>)}</tbody></table></div><a href="/data/verified-snapshot.json" target="_blank" rel="noreferrer">Historical provenance</a></details>
 <p className="attribution">Town concept inspired by <a href="https://sael.net/token-town/" target="_blank" rel="noreferrer">Ryan Sael’s Token Town</a>. Original visualization. Selected networks and products, not the entire ecosystem. No affiliation with the named organizations.</p>
 </dialog>
}
